### ISSUE TITLE
Retraction Tower Script Not Working

### ISSUE THREAD

**Issue by smartalx** [5axes/Calibration-Shapes#100]
Maybe I'm not understanding how this post processing gcode is supposed to work, but I'm sure I followed the instructions on the wiki.  And maybe I'm wrong but as I understand it a retraction is a G1 code with a negative E value.  I'm checking the produced g-code and I don't see any "E-" codes produced for the retraction tower, except for the start and end of the file.  Plus when I slice the model without the post processing gcode, there's no change in the print time and no change in the retraction time compared to when I slice the model with the post processing gcode.  I'm pretty sure I'm doing everything right.

Now I am using a 0.6 nozzle but I put a check in the "Remove all holes" parameter as instructed.
Cura 4.13.1

![ret tower not working1](https://user-images.githubusercontent.com/34923907/172565838-26751f08-d044-407d-aeff-3d4c2ef498de.png)
![ret tower not working2](https://user-images.githubusercontent.com/34923907/172565844-27e84ac8-3126-467c-9c1b-b4bffb2fd320.png)

**Comment by 5axes** [comment]
The name of these scripts are "Postprocessing" script. This means that they are activated at the time of postprocessing the Gcode, i.e. at the time of writing the final code. So there is no modification of the informations in Cura. The only way to see if the script works is to compare two Gcode files or to reload the Gcode in a Gcode Viewer.
![image](https://user-images.githubusercontent.com/11015345/172577856-4532e4a8-524c-44ce-bd2c-235d89b03d7c.png)

**Comment by 5axes** [comment]
**Additional note :** 
The retraction **must be activated** in the Cura Project. If you don't have any E code in your file, that's the origine of the issue.
In the Gcode if you have activated the option "Display Detail on LCD" You should find some **M117** instructions in the GCode.

![image](https://user-images.githubusercontent.com/11015345/172579449-5c0359ce-6620-41f5-b5a3-65a1ae329c54.png)

**Comment by smartalx** [comment]
I did look at the gcode.  And retractions is turned on.

**Comment by smartalx** [comment]
There are M117 instructions in the code.  But there are only 3 lines with "E-", which as I understand it is the retraction.  E for extruder.  Negative number means retract instead of extrude.  The value will be how many millimeters to retract.  I see 1 example at the top of the gcode before the print starts and 2 at the bottom after the print is done.

**Comment by 5axes** [comment]
Vous devez partager votre projet pour l'analyser. Sans exemple impossible d'analyser votre problème.

**Comment by smartalx** [comment]
I don't understand.  My project is the retraction tower.  Do you mean the gcode?

**Comment by smartalx** [comment]
dammit
no
I must have uploaded the wrong files.  I switched to the retraction test because I couldn't wait 3 days to run the calibration tower.

**Comment by smartalx** [comment]
The 3mf file doesn't create retractions.

**Comment by smartalx** [comment]
But that's just a smaller extrusion.  Is a smaller extrusion the same thing as a retraction?  I thought a retraction was a gcode like:
G1 F2700 E-1
And there are only three of those "E-" occurrences in the file...
None of them during the printing of the layers.

The reason I even noticed this is the retraction towers I printed don't change at each level.  There's no visible difference between the stringing at the lower level and the higher level.  But I'm experiencing retraction problems with my normal prints.  So I need a retraction tower that shows me the problems at 1mm up to 6mm or up to 10mm so I can figure out which one works for my printer.  And the calibration tower doesn't work for that.  All of the towers look identical, whether the retraction is 1 or even if it's as high as 10!

**Comment by 5axes** [comment]
I don't doubt that you have a retraction and stringing problem. But it's a problem between your machine and your filament. Not a script problem in this case. 

On my point of view you should first of all have a look to the parameter on the maximum Extruder speed on Ender-3 . 25 mm/s is not enough try to increase to 50mm/s

**Comment by hayden-t** [comment]
I was wondering about this too, as my tower seemed fine on all layers, i tried looking for the E- commands too and could not find them, but did find the lcd lines.  thanks

**Comment by 5axes** [comment]
If you have the lcd lines. Then the script is working. Stringing is not an issue for everyone. Sometimes just with the minimal value you don't have any issue so with or without change the result looks correct on every section. The first step is to tune your printing temperature via the temptower. A low temperature could produce a nice visual part, low stringing but could generate a poor adhesion   between layers. Definin
g the right profile is sometimes a long process, that's why the plugin is offering so much test parts
