### ISSUE TITLE
Linear Advance & Acceleration & Ringing Tower

### ISSUE THREAD

**Issue by traviselam** [5axes/Calibration-Shapes#102]
Just wondering if the readme for the Acceleration & Ringing Tower should mention disabling linear advance in Marlin firmware. 
The link in the  readme (https://www.klipper3d.org/Resonance_Compensation.html) mentions disabling pressure advance. This is called "Linear Advance" in Marlin.

**Comment by 5axes** [comment]
Hello,

As I don't have this feature on the Marlin of my machine (Ender-3) I cannot have an opininion on your request. Other advice will be welcome.

**Comment by traviselam** [comment]
Gotcha. Yeah, I just updated to the latest Marlin firmware on my machine (Ender 3) and I've enabled linear advance when compiling the firmware. I just wanted to make you aware of it just in case. Thank you so much for the excellent plugin! The shapes and tests have helped me so much already!
