### ISSUE TITLE
[Feature Request] PETG Temp Tower

### ISSUE THREAD

**Issue by hawkeyexp** [5axes/Calibration-Shapes#11]
Hi,

first to say: great plugin!!!

Would be nice if you can add more temp towers for different materials - but i think the big three pla / abs / petg is the most needed - so only petg is missing :-)

**Comment by 5axes** [comment]
Updated in V1.0.8

**Comment by userosos** [comment]
I add the tower - part for calibration/PETg temp tower. Add chage g-code Tempfan tower. And it not work.

[Untitled.zip](https://github.com/5axes/Calibration-Shapes/files/6097311/Untitled.zip)

**Comment by 5axes** [comment]
Looks like you set the wrong parameter in the script .. When we log your GCode change are made every 3 steps.
![image](https://user-images.githubusercontent.com/11015345/110248230-58559300-7f70-11eb-87b9-a5c62b62d0e0.png)

As your settings for the layer Height are set to : 
- First layer height : 0.3
- Layer height : 0.2

![image](https://user-images.githubusercontent.com/11015345/110248272-81762380-7f70-11eb-98eb-149a1b51c3c2.png)

In this case settings must be : 

![image](https://user-images.githubusercontent.com/11015345/110248355-ecbff580-7f70-11eb-93d7-af7bcd6e66cf.png)

And you should get these result :  
![image](https://user-images.githubusercontent.com/11015345/110248391-17aa4980-7f71-11eb-907b-eabb7cc8709f.png)

**Comment by userosos** [comment]
I use default settings
![изображение](https://user-images.githubusercontent.com/22872748/110254323-c6657e80-7f9f-11eb-9260-c8376b052ed0.png)

**Comment by 5axes** [comment]
Ok that's normal you should not use the Fan option, that's why you have the same temperature on 3 level. Read the wiki concerning the script options

**Comment by userosos** [comment]
> 
> 
> Ok that's normal you should not use the Fan option, that's why you have the same temperature on 3 level. Read the wiki concerning the script options

It works! Thx!

**Comment by 5axes** [comment]
Updated in V1.0.8
