### ISSUE TITLE
Retract Tower distance test fails

### ISSUE THREAD

**Issue by pierremilcent** [5axes/Calibration-Shapes#115]
I built a retratct tower project to validate which distance best fits the printer (Sidewinder X2).
The printer is a direct drive, with BLTouch.

I don't understand why the extruder motor is running so fast and long, while i only configured 0.25mm retraction at first with 0.25 increment. default speed is 25mm/s.

<img width="1145" alt="Capture d’écran 2022-09-13 à 15 11 41" src="https://user-images.githubusercontent.com/38214885/189932792-c7f6113e-6188-4aa4-a96c-71d9a237ec46.png">

I aleady build a Retract Test with the calibration plugin (which is updated to the latest version and it works fine, as a temp tower.

Could you have a look at this 1mn video https://youtu.be/I-RQWQdmti4 

I also attach the gcode file if needed. Thanks for your support.

[RetractTower Cura 5.1.gcode.zip](https://github.com/5axes/Calibration-Shapes/files/9558195/RetractTower.Cura.5.1.gcode.zip)

**Comment by 5axes** [comment]
Yes there is a problem
![image](https://user-images.githubusercontent.com/11015345/189933405-ce654c9b-27ef-41e9-98a5-fb227b382afe.png)

Version of the plugin ?

**Comment by 5axes** [comment]
Ok I got it ...
![image](https://user-images.githubusercontent.com/11015345/189936440-cd46f4f1-5d6c-48a8-b210-424f22b8d8db.png)

Someone I don't know who found the good idea to add the Code M83 (relative extrusion) but commented in the Start Gcode. Unfortunately the Script detects this code and switches the extrusion to Relative mode.   

![image](https://user-images.githubusercontent.com/11015345/189937196-cee0aca0-1a23-4596-bdd7-526c6fdc8464.png)


Solution N°1 remove this line temporarily
Solution N°2 modify the script in a next version

**Comment by pierremilcent** [comment]
By the way i see you are using prusaslicer to view the gcode and you are able to see extruder activities : yellow and orange lines i guess ...
Can you share which option in prusaslicer are you using for such purpose ? Thanks.

**Comment by 5axes** [comment]
I don't use PrusaSlicer but SuperSlicer .. It's much more advanced compare to PrusaSlicer

**Comment by pierremilcent** [comment]
I am also trying this version despite it is not well designed for my Mac ... and how to view these feature in SuperSlicer ?

**Comment by 5axes** [comment]
Use the Superslicer-Gcodeviewer , Type of functionnality  and  then in option you can also specify Retractions / Deretractions etc etc  You need to play qith the different options.

**Comment by pierremilcent** [comment]
Thanks. You're right SuperSlicer does show more than PrusaSlicer. But it 

PrusaSlicer
<img width="778" alt="Capture d’écran 2022-09-13 à 18 27 02" src="https://user-images.githubusercontent.com/38214885/189956146-93b17f6d-94c6-49b9-a809-22d23984a98a.png">

SuperSlicer
<img width="924" alt="Capture d’écran 2022-09-13 à 18 26 20" src="https://user-images.githubusercontent.com/38214885/189956200-ef48c22f-b126-46d6-8ab7-9e6db29b94f6.png">

Here i can see on the left that E value is far too large ...
<img width="906" alt="Capture d’écran 2022-09-13 à 18 30 23" src="https://user-images.githubusercontent.com/38214885/189956688-ef1129b1-ca58-48ca-b647-a2a48ed73ff3.png">

**Comment by 5axes** [comment]
**PrusaSlicer** 

![image](https://user-images.githubusercontent.com/11015345/189959023-92cbb3a8-1684-42ee-b237-c47b72c0a65b.png)

**SuperSlicer** 

![image](https://user-images.githubusercontent.com/11015345/189958946-a5b3ddc6-a38b-4b0f-922e-86d3a9d7a830.png)

+ not visible Feature like G02/G03 in SuperSlicer not in Prusa  and other functions but I forgot the exact list

**Comment by pierremilcent** [comment]
Working. Solved. Thks

![IMG_2953](https://user-images.githubusercontent.com/38214885/189961432-6da004d3-25e9-4703-9242-564abed3efed.jpg)
