### ISSUE TITLE
[Feature Request] First layer test

### ISSUE THREAD

**Issue by MonDroone** [5axes/Calibration-Shapes#14]
Hello
is it possible to add a test for the first layer like this one http://www.thingiverse.com/thing:2177790 
thank you for this very practical module
Christophe

**Comment by 5axes** [comment]
Hello,

Thanks for your comment, As we already have a first layer test : [https://github.com/5axes/Calibration-Shapes/wiki/ParametricBedLevel](https://github.com/5axes/Calibration-Shapes/wiki/ParametricBedLevel) . And as we cannot add every existing geometry, it's possible but you have to demonstarte why your solution is better than the existing one.

**Comment by 5axes** [comment]
whitout answer , I think I can close it
