### ISSUE TITLE
Store models in binary stl instead of ascii stl

### ISSUE THREAD

**Issue by nallath** [5axes/Calibration-Shapes#17]
As per title. Binary STL is much smaller than ascii stl. It won't make that much differnce for the small models, but it does add up for the larger ones.

**Comment by 5axes** [comment]
Yes you are right but as I want to keep OpenScad as reference  (like that anyone would be able to modify the design and why not suggest a better design :  shorter or more revelant for the test)  and As OpenScad Only generate an Ascii STL file ( or I'm missing something in the options of OpenScad).  

It could be a good solution if in cura It makes a big difference to load an ascii or a binary file via the trimesh library, but the test I've made doesn't seems to show any significant difference.

**Comment by 5axes** [comment]
Finaly it's a not a bad idea ... Drag and Drop in Cura and Export of the STL file will offer the possibility to reset automaticaly the position to 0 , 0 .. I Will convert the file for the next release

**Comment by 5axes** [comment]
STL file Converted to STL binary except for Dual extruder sample part.
