### ISSUE TITLE
Temperature tower does not work with nozzle size of 0.8. it does not slice properly.

### ISSUE THREAD

**Issue by AlexZan** [5axes/Calibration-Shapes#19]

**Comment by 5axes** [comment]
It s designed for a 0.4 nozzle, if you want to use it with a 0 8 nozel change the size by using the Cura scalling function

**Comment by MarphXL** [comment]
Perhaps you could give us a config-attribute for nozzle-size? It would be great. And thanks for your work: amazing: I love this plugin

**Comment by 5axes** [comment]
Can you developped what do you mean by "config-attribute" ?

**Comment by MarphXL** [comment]
Hi, in the cura-menu you have a menu-option "define default size". 
Perhaps you can add a menu-option "nozzle size"

**Comment by 5axes** [comment]
In this case we can directly get this information from the Cura settings 
![image](https://user-images.githubusercontent.com/11015345/118415194-44818800-b6a9-11eb-9645-2456ec896842.png)

But this is not the real problem ...  If I add a design for let say the most common nozzle Size ...  0.2  0.4  0.6  0.8 and Why not 1.2 that's a uge number of part for just a limited number of user .   I think it's a simpler solution to keep the same geometry and if someone wants to use a 0.8 nozzle it can do it just by activating the option "Remove all holes"  in the Mesh fixe section. 
![image](https://user-images.githubusercontent.com/11015345/118415358-25cfc100-b6aa-11eb-863b-2e2fb9b845d0.png)

And in this case the actual geometry can be also be used with a 1.2 nozzle diameter.
![image](https://user-images.githubusercontent.com/11015345/118415423-83fca400-b6aa-11eb-9334-cf4d82d153b8.png)

**Comment by 5axes** [comment]
Solved in V1.3 by changing automaticaly  the <code>Remove All Holes</code> in the settings in such case
