### ISSUE TITLE
After installing the calibration shapes plugin in Cura 4.8 and after restarting Cura

### ISSUE THREAD

**Issue by vin024github** [5axes/Calibration-Shapes#20]
I installed the Cura plugin calibration shapes but after Cura 4.8 restart, i can get the Add a Retract Tower but when i go to Post Processing and Modify G-Code menu, i dont see the script for editing the parameters in the list of scripts. Operating system MacOS Sierra 10.12.6

**Comment by 5axes** [comment]
Did you use thefunction copy scripts to add the scripts to the right place ?

**Comment by 5axes** [comment]
Whitout news .. don't need to keep it open
