### ISSUE TITLE
Modified G-Code not included...

### ISSUE THREAD

**Issue by Benvolio28** [5axes/Calibration-Shapes#21]
Hi!  Love the tools, however for the temperature tower, the modified G-Code is not part of the project.  The temp just stays the same as my cura settings. I'm on an Ender 3 V2 (running the Smith 3D software), with Cura 4.8.0.

I have installed the plug in
I have added the modified G-Code to Cura
I have restarted Cura.

Thanks for your help, and thank you for the plugin!

**Comment by 5axes** [comment]
There is no modified G-code in this plugin. I don't really understand what kind of issue you are talking about ?

**Comment by Benvolio28** [comment]
With the temp tower, it does not alter the temp for each step.  It stays at
the temp set in my cura settings. So, I usually print pla at 200... So,
it's always 200.  No variance.

Thanks for your reply.

**Comment by 5axes** [comment]
did you add the TempFan postprocessing script and configure it ?

**Comment by AlexZan** [comment]
I have the same issue, I have added the TempFan script and there is only one single m109 command in the gcode

**Comment by Benvolio28** [comment]
So sorry it took me a bit to get back to you... work got in the way.
Yes, I did add the TempFan script and configure it

**Comment by 5axes** [comment]
Ok i haven't correctly read your first message. I don't know what is this "Smith 3D software"  the script are designed for a Marlin compatible printer. Could be the origine of your issue ?

**Comment by XAMCTBO** [comment]
guy`s I have totally same issue like guy who create subject. Cura 4.8 adding this plugin, restart cura, adding modifyed G code  setting up layers and start temp, push slice -> send to octoprint - temperature not changing.... 
Octopi updated 
cura connected to octoprint(latest)

**Comment by 5axes** [comment]
Whitout news .. don't need to keep it open
