### ISSUE TITLE
Copy Scripts does not work

### ISSUE THREAD

**Issue by pierremilcent** [5axes/Calibration-Shapes#26]
After updating Calibration Scripts to 1.2.2 the copy of scripts does not work : seems related to a sub directory as shown on screenshots

![2021-04-08 14_07_08-Untitled - Ultimaker Cura 4 8 0](https://user-images.githubusercontent.com/38214885/114024183-0906c900-9874-11eb-8351-8b5189ba57a6.png)

![2021-04-08 14_10_24-Clipboard](https://user-images.githubusercontent.com/38214885/114024453-5e42da80-9874-11eb-94e6-5cbb0008739d.png)

**Comment by 5axes** [comment]
1.2.2 ??? last release 1.2.1 ?

**Comment by pierremilcent** [comment]
Oups .... latest installe is 1.2.0 despite the market place is still behind this version ...

![2021-04-08 14_27_06-Greenshot](https://user-images.githubusercontent.com/38214885/114026542-a4993900-9876-11eb-919b-df05b6a95653.png)
![2021-04-08 14_27_13-Greenshot](https://user-images.githubusercontent.com/38214885/114026549-a6fb9300-9876-11eb-894a-d935717c5260.png)

**Comment by 5axes** [comment]
try with the 1.2.1

**Comment by 5axes** [comment]
try with the 1.2.1

**Comment by pierremilcent** [comment]
It seems to be solved with this version. 2 scripts updated (retracttower and speedtower).

![2021-04-08 16_35_20-scripts](https://user-images.githubusercontent.com/38214885/114045752-8f2d0a80-9888-11eb-9db8-63f1fff3decd.png)

**Comment by 5axes** [comment]
Ok the Scripts\Scripts displayed in the final message is just an Error in the messsage text not in the real destination Folder.  Solved in 1.2.2

**Comment by 5axes** [comment]
Ok the Scripts\Scripts displayed in the final message is just an Error in the messsage text not in the real destination Folder. Solved in 1.2.2
