### ISSUE TITLE
[New feature] Add a calibration shape for bed first layer

### ISSUE THREAD

**Issue by lwiart** [5axes/Calibration-Shapes#29]
Hey,

I'm fond of your plugin for Cura, that I go to for anything related to calibration!
And I'm wondering if at some point in the future you could add a shape for the calibration of first layer/bed leveling?

Something along those lines:
https://www.thingiverse.com/thing:34558
https://www.thingiverse.com/thing:4714033
https://www.thingiverse.com/thing:2280529
https://www.thingiverse.com/thing:1306709
Or whatever you would deem as fitting the purpose.

Maybe it already exists and I missed it. Sorry if this is the case.

Many thanks.

**Comment by 5axes** [comment]
Yes  we already have a shape to calibrate the first level : it ' s call Bed Level Calibration : https://github.com/5axes/Calibration-Shapes/wiki/ParametricBedLevel
