### ISSUE TITLE
Objects are placed with their center on the buildplate

### ISSUE THREAD

**Issue by nallath** [5axes/Calibration-Shapes#3]
Cura version: Master

I don't have "automatically drop to buildplate" enabled, which means that the calibration shapes are created with their center on top of the build plate.

Since Cura loads all models with their bottom on the buildplate (even if the drop to buildplate isn't enabled), I'd expect the objects to always be there. It's a minor issue since it doesn't really impact the functionality of the plugin

**Comment by 5axes** [comment]
Yes it's really a minor issue, But as any comment are welcome I will translate these models on the Z=0 of the build plate.

**Comment by 5axes** [comment]
Change in V1.0.5
