### ISSUE TITLE
Temp Tower 220-185, so what's 175 for?

### ISSUE THREAD

**Issue by jagauthier** [5axes/Calibration-Shapes#40]
I installed this plugin, and created the temp tower.  I followed the guidance here:
https://github.com/5axes/Calibration-Shapes/wiki/PLA-TempTower-220---180%C2%B0C

![image](https://user-images.githubusercontent.com/7101432/119370337-2ad0d980-bc83-11eb-93fb-9b124430e0cd.png)

When I inspected the gcode afterwards (to verify post-processing) I see the temperature actually goes down to 175.

```
;TYPE:CUSTOM TEMP
M104 S175
;TYPE:WALL-INNER
;MESH:PLATempTower
G1 F1800 E2362.62502
G1 F1200 X121.792 Y113.42 E2362.65192
G1 X119.917 Y113.42
;TYPE:WALL-INNER
;BRIDGE
G1 F600 X101.503 Y113.42 E2362.8356
```

Did I do something wrong?

**Comment by 5axes** [comment]
Your cura settings must be linked to this default value : IE Change Layer ->52  and Change Layer Offset -> 5

Cura **Layer height** = **0.16**   and check that the option **_Use Adaptative Layer_** is **not** active

**Comment by jagauthier** [comment]
It was the adaptive layer!  thanks!

**Comment by 5axes** [comment]
Yes it's a common issue, most of the Creality user who are using the default **_Dynamic Quality_** profile doesn't notice that this profile also activated this parameter (assuming you are one of this Creality user).

![image](https://user-images.githubusercontent.com/11015345/119375326-f8db6980-bcba-11eb-8f1e-8ce94fe53d15.png)
