### ISSUE TITLE
Temp Towers: Gaps between steps make it unprintable

### ISSUE THREAD

**Issue by alexvonsiebenthal** [5axes/Calibration-Shapes#41]
can't print the temp towers with the most recent version. The object has gaps/spaces between each temp step.
![cura_heattower](https://user-images.githubusercontent.com/6860125/119480036-88cbf280-bd51-11eb-90e3-e8d2e0e64de4.jpeg)

**Comment by 5axes** [comment]
Nozzle size ?

**Comment by alexvonsiebenthal** [comment]
> Nozzle size ?

.6
But why should that fail the STL? Other STLs of similar towers work just fine.

**Comment by 5axes** [comment]
The design of these tower are made for a 0.4 nozzle. If you want to use them, with  a bigger nozzle  use the option 
https://github.com/5axes/Calibration-Shapes/issues/19#issuecomment-841889515

**Comment by alexvonsiebenthal** [comment]
Indeed, the Remove All Holes options works. Thank you.

**Comment by 5axes** [comment]
Next release will automatically activate this function in such situation V1.2.5
