### ISSUE TITLE
Extreme extrude feed at end of retraction tower

### ISSUE THREAD

**Issue by OctavioBs** [5axes/Calibration-Shapes#46]
When doing a retraction tower, just in the moment the part has finished I get a vary fast and generous feed on the extruder, so fast that even the extruder stepper gets blocked (e3d Hemera).
![Imagen 15](https://user-images.githubusercontent.com/31729287/124351131-e0833680-dbf8-11eb-9726-2958a0a04b2c.jpeg)
![Imagen 16](https://user-images.githubusercontent.com/31729287/124351137-e416bd80-dbf8-11eb-9b84-36f1a11e7b35.jpeg)
[stringing 025 to 125-0.4-PLA T 004448-205C.txt](https://github.com/5axes/Calibration-Shapes/files/6758210/stringing.025.to.125-0.4-PLA.T.004448-205C.txt)

Excuse me if something is done wrong as this is the first time i open an issue on github.

**Comment by 5axes** [comment]
Do you use the last version of the script ?

**Comment by OctavioBs** [comment]
Yes, 1.3.3

<img width="647" alt="Captura de pantalla 2021-07-03 a las 19 12 28" src="https://user-images.githubusercontent.com/31729287/124361991-acc50280-dc32-11eb-93ca-b864dce2cd5d.png">

**Comment by 5axes** [comment]
This problem should not exist anymore. Did you copy the last script in the script directory ? And can you check by opening the RetractTower.py file that this is the release 1.5 ?

![image](https://user-images.githubusercontent.com/11015345/124473067-27ab2c00-dd9f-11eb-87ac-fa275ac8fe1c.png)

**Comment by OctavioBs** [comment]
Now it works perfectly, excuse me for the delay but was travelling due to my job.
