### ISSUE TITLE
Copy scripts not available

### ISSUE THREAD

**Issue by locotodd** [5axes/Calibration-Shapes#59]
I just installed the plugin, and have rebooted Cura multiple times.  But the copy scripts option does not appear in the drop down.

![image](https://user-images.githubusercontent.com/91097083/134080344-ae9b27de-8a79-46ab-a72f-0fbf5254a1b4.png)

**Comment by 5axes** [comment]
If the menu is not visible it's because you don't need anymore. Since Cura 4.9 and a bug correction in Cura the scripts should be avalaible even if you don't copy them into the scripts directory.
