### ISSUE TITLE
[Request] Add Ringing Tower (Resonance Compensation)

### ISSUE THREAD

**Issue by tispokes** [5axes/Calibration-Shapes#74]
Hi, I'm currently wanting to add ADXL345 accelerometers  to my FDM printer.

For testings I need the Ringing Tower (https://www.klipper3d.org/Resonance_Compensation.html)
Would be nice if implemented into this superior plugin in the future.

**Comment by 5axes** [comment]
Nice idea ... Need investigation

**Comment by tispokes** [comment]
Nice, I printed it just 10 minutes ago 😅👍

Thanks

**Comment by 5axes** [comment]
Included in V1.7
