### ISSUE TITLE
Temperature Tower Walls Too Thin?

### ISSUE THREAD

**Issue by PICKLEBOY** [5axes/Calibration-Shapes#78]
I am attempting to run the temperature tower for PLA+ and Cura is not slicing the entire model (Cura Version 4.12.1). From what I can tell it has to do with how thin the walls are on the Temperature tower? I am using a 0.4mm nozzle and have my line width set to 0.4 and this is what Cura does when I try to slice it. It does this with all of the temp towers. If I change the line width to 0.1 all of it will slice, but I do not have a nozzle that size.
![tqrj7ibubbb81](https://user-images.githubusercontent.com/13538958/149221545-3c0a770f-b267-4380-869b-b21c989aba19.png)

I have been following this tutorial https://www.youtube.com/watch?v=EAG_538k_bM.

**Comment by 5axes** [comment]
Well Chep Sometimes is not good for everything.  Set the Outer Wall Inset parameter to 0 as it should be by default And it will be ok



----- Mail original -----
De: "PICKLEBOY" ***@***.***>
À: "5axes/Calibration-Shapes" ***@***.***>
Cc: "Subscribed" ***@***.***>
Envoyé: Mercredi 12 Janvier 2022 22:10:05
Objet: [5axes/Calibration-Shapes] Temperature Tower Walls Too Thin? (Issue #78)





I am attempting to run the temperature tower for PLA+ and Cura is not slicing the entire model (Cura Version 4.12.1). From what I can tell it has to do with how thin the walls are on the Temperature tower? I am using a 0.4mm nozzle and have my line width set to 0.4 and this is what Cura does when I try to slice it. It does this with all of the temp towers. If I change the line width to 0.1 all of it will slice, but I do not have a nozzle that size. 
tqrj7ibubbb81

I have been following this tutorial https://www.youtube.com/watch?v=EAG_538k_bM . 

— 
Reply to this email directly, view it on GitHub , or unsubscribe . 
Triage notifications on the go with GitHub Mobile for iOS or Android .

**Comment by PICKLEBOY** [comment]
Thank you for that! It will slice now.
