### ISSUE TITLE
Temp tower script not working

### ISSUE THREAD

**Issue by JaVelin-X** [5axes/Calibration-Shapes#89]
In Cura 4.12 I am trying to print a temp tower but I noticed the script wasn't changing the temperature as it was printing. I checked it by searching for M104 and they are not being added that I can find. I see the temp is not changing on the printers screen as it prints

**Comment by 5axes** [comment]
Pebcak

**Comment by JaVelin-X** [comment]
Works on one PC but not this one...
![image](https://user-images.githubusercontent.com/79427229/155887606-6df8c49c-a257-4c84-8ed7-de1ca9ee7983.png)
![image](https://user-images.githubusercontent.com/79427229/155887620-2600358b-121f-4e65-b295-24c720438e76.png)

**Comment by 5axes** [comment]
Don"t know what is this big 3d format . But the script are just for text and Marlin format.

**Comment by JaVelin-X** [comment]
the second PC .. i'll try with regular Cura format on the sho computer too if you think it makes a difference. BTT one jjsy embeds a thumbnail of the model.

![image](https://user-images.githubusercontent.com/79427229/155890369-b62efca8-07cf-454d-a266-d8307be99f81.png)

**Comment by JaVelin-X** [comment]
yes with all other add-ons disabled. the temperature scrip doesn't work on this PC but the changeAtZ script does

**Comment by 5axes** [comment]
Sorry absolutly no idea, you will be oblige to investigate by yourself.

**Comment by e-SonOfAnder** [comment]
I am experiencing this same issue - Cura 4.13.1, add temp tower, add script, and after slicing the resulting gcode does not contain any of the M104 commands to change the temperature during the print. The retraction distance calibration item worked, but I am unconvinced the retraction speed one worked either, as the full print came out with no issues, but I have not looked at that gcode yet. The Calibration Shapes is the only extension I have installed from the Cura marketplace.

If there are logs or any additional diagnostic information I can provide, please let me know as I'd be happy to do so.

**Comment by 5axes** [comment]
Screenshot of your script settings ?

**Comment by e-SonOfAnder** [comment]
Here you go:

https://imgur.com/a/9nU5mqR

**Comment by e-SonOfAnder** [comment]
Just ran it again this morning, and it seems to have worked; this may be a Cura bug requiring it be closed completely between projects (similar to the current open one that causes Cura to be unusable if you tell it to open a gcode file until you close and restart it).

**Comment by 5axes** [comment]
I don't know, Everything seem's to be correct in your settings. Should be ok directly without need to restart.

**Comment by DarokCx** [comment]
Similar problem here. Using a .6mm nozzle with .4mm layer height. set tempfan tower to change at each 20 layer, but in reality it does every 40 layers or so. Seems it looks for a certain z height instead of layer number.

**Comment by jvolker** [comment]
Same in Cura 5.0.0

**Comment by 5axes** [comment]
tested again right now in Cura 5.0.0 works fine for me.
![image](https://user-images.githubusercontent.com/11015345/169517340-e7e0858c-c4ea-46e4-87ed-034555471235.png)

**Comment by jvolker** [comment]
I'm sorry, I just realized I first didn't use any post-processing script and I was then not using the right script. It seems to work now. Could be good to give a hint after adding a temperature tower or activate the post processing script automatically.

Thanks.

**Comment by 5axes** [comment]
@5axes how did you get the color scheme to represent temperatures? -> I'm Using a GCode Viewer  ( SuperSlicer GCode Viewer) 
https://github.com/supermerill/SuperSlicer

**Comment by 5axes** [comment]
I think I can close this issue now
