### ISSUE TITLE
Wrong instructions at the Acceleration page

### ISSUE THREAD

**Issue by luizbgomide** [5axes/Calibration-Shapes#90]
The instructions for Jerk and Acceleration says to leave them on for the test, but it they are on, they overload every change in the layer:
![image](https://user-images.githubusercontent.com/18707781/156429203-34777002-047b-4d8d-a601-5e0858565be0.png)

```
;TIME_ELAPSED:623.259693
;LAYER:25
M117 INDICATOR-Layer25
M117 DASHBOARD_LAYER_INDICATOR 26
;TYPE:CUSTOM VALUE
M205 X10 Y10
M117 Jerk X10 Y10
M204 S500
M205 X8 Y8
;TYPE:WALL-OUTER
;MESH:AccelerationTower
```
The `M205 X8 Y8` is set by the Enable Jerk Control setting and is overloading the previous M205 for the test.

**Comment by 5axes** [comment]
Fixed ! Thanks for the report.
