### ISSUE TITLE
Feature request: write text

### ISSUE THREAD

**Issue by ImagineerNL** [5axes/Calibration-Shapes#91]
Might not be a specific calibration thing, but would be used for calibrating different stls.

Usecase; i have multiple versions of the same item; for example scaled 99 / 100 / 101 percent for making a tight fit.
However, on the print plate it can be hard to see the difference between them. When it is using a different infill it's even harder since the differences arent visual.

It would help a lot to be able to add 1layer thick text-meshes, so i can 'annotate' on the buildplate next to the mesh and be able to see it next to the finished print a couple of hours later. 
No need for special things as font etc, just a solid straight font like arial bold will do.

**Comment by 5axes** [comment]
Nice idea,  Perhaps not a free text filed but just a mark
![image](https://user-images.githubusercontent.com/11015345/156882569-08e51184-cdcf-49e0-9cc7-7342a4c26600.png)

**Comment by ImagineerNL** [comment]
That would be perfect already, awesome

**Comment by 5axes** [comment]
ok adding for the next release. you need to select each geometry. the selection order is important because the number will be fixed according to the selection order.
![image](https://user-images.githubusercontent.com/11015345/156888967-7d41fc1f-a974-4516-ad53-646b96142d8e.png)

**Comment by 5axes** [comment]
https://github.com/5axes/Calibration-Shapes/releases/tag/V1.9.0

**Comment by ImagineerNL** [comment]
Thank you very much!

**Comment by 5axes** [comment]
Function removed from the Calibration Plugin and integrated into a new Plugin dedicate to this type of function : [NameIt](https://github.com/5axes/NameIt)

**Comment by ImagineerNL** [comment]
You're awesome!
