### ISSUE TITLE
PLA Temp Tower 220-180

### ISSUE THREAD

**Issue by Willemthefirst** [5axes/Calibration-Shapes#99]
Hello,
I tryed the Temp Tower twice with different Filament. On the Backside right hand inner corner there are always two little line to long.
See Picture.
![20220531_144446](https://user-images.githubusercontent.com/57330263/171264138-92489d77-0592-4966-ae1d-c091a4f325e5.jpg)
Willemthefirst

**Comment by 5axes** [comment]
Cura 4.x or Cura 5.0 ?

**Comment by 5axes** [comment]
Could be an issue in this case with the parameter :  "Wall Ordering"   the default value brings a lot of problem. Try to set this value to "Inside To Outside".

**Comment by Willemthefirst** [comment]
Thanks, I'll check it out.

5axes ***@***.***> schrieb am Mi., 1. Juni 2022, 09:38:

**Comment by Willemthefirst** [comment]
Hello, in my case it was the check on "Optimize Wall Printing Order".
Unchecked that and the corner is ok now.
So thanks again for the fast answer

Kurt

Am Mi., 1. Juni 2022 um 09:41 Uhr schrieb Kurt Hennig ***@***.***>:
